# Blockchain configuration for casino games
# You can override these values using environment variables

default: &default
  # RPC endpoint for blockchain connection
  rpc_url: "https://carrot.megaeth.com/rpc"
  
  # Contract configuration
  contract_address: "0x2Bd3e4Afc924919BC0fE5e1b448160B2bF2d91b7"
  contract_abi_name: "two_party_war_game"
  
  # Smart sync configuration
  sync_schedule_ms: 10000
  max_games_to_process: 20

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  # Production-specific overrides can go here
  # Use environment variables to override these values
  # rpc_url: "your-production-rpc-url"
  # contract_address: "your-production-contract-address"
