# Blockchain configuration for casino games
# You can override these values using environment variables

default: &default
  rpc_url: "https://carrot.megaeth.com/rpc"
  contract_address: "0x64d71A67f0F8803BA5f41CE6893917D3Df105FBe"
  contract_abi_name: "two_party_war_game"
  block_explorer_url: "https://megaeth-testnet.blockscout.com/address/"
  sync_schedule_ms: 10000
  max_games_to_process: 20
  blockscout_api_limit: 50  # number of transactions per blockscout API request
  poll_update_interval: 60  # seconds between blockchain polls
  telegram_message_interval: 300  # seconds between aggregated telegram messages

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  # Production-specific overrides can go here
  # Use environment variables to override these values
  # rpc_url: "your-production-rpc-url"
  # contract_address: "your-production-contract-address"
